name: Verify

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/DualMind.API/DualMind.API.csproj
    - name: Build
      run: dotnet build src/DualMind.API/DualMind.API.csproj --no-restore
    - name: Test
      run: dotnet test tests/DualMind.API.Tests/DualMind.API.Tests.csproj --no-build --verbosity normal
